* HTML

** 入门
  
** head

   <head> 元素与 <body> 元素不同，它的内容不会在浏览器中显示

*** title

	<title> 元素是一项元数据，用于表示整个 HTML 文档的标题（而不是文档内容）

*** meta

	<meta charset="utf-8">

	许多<meta> 元素包含了name 和 content 特性：
	  name 指定了meta 元素的类型； 说明该元素包含了什么类型的信息。
	  content 指定了实际的元数据内容

	设置主语言：
	  <html lang="zh-CN">

** 文字处理

   <p> 段落 </p>
   <h1>我是文章的标题</h1>

   <h1>、<h2>、<h3>、<h4>、<h5>、<h6>
     <h1> 表示主标题（the main heading）
	 <h2> 表示二级子标题（subheadings）
	 <h3> 表示三级子标题（sub-subheadings），等等。


   可以让任一元素看起来像一个顶级标题，如下：
   <span style="font-size: 32px; margin: 21px 0;">这是顶级标题吗？</span>
   这是一个 <span> 元素，它没有语义。


   <ul> <li> 无序列表
   <ul> <li> 有序列表

   <em> （emphasis）元素来标记强调，默认斜体
   <strong>  (strong importance) 来标记非常重要，默认粗体
   粗体风格，你应该使用<span>元素和一些CSS，或者是 <b> 元素

   
    <i> 被用来传达传统上用斜体表达的意义：外国文字，分类名称，技术术语，一种思想……
    <b> 被用来传达传统上用粗体表达的意义：关键字，产品名称，引导句……
    <u> 被用来传达传统上用下划线表达的意义：专有名词，拼写错误……

   
** 超链接

   <a>

   块级元素，变成超链接

   链接到文档内部
     用#号指向ID

*** 绝对url 和 相对url

*** 非html 资源

	下载链接时， 需要使用download 属性

	<a href="https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=zh-CN"
	download="firefox-latest-64bit-installer.exe">
	下载最新的 Firefox 中文版 - Windows（64位）
	</a>
   
*** 电子邮件链接

** 高阶文字排版

*** 描述列表

	<dl>  description list 描述列表 
	<dt>  description item
	<dd>  description definition

*** 引用

	<blockquote> 块级引用
	<q>  行内引用
	<cite> 引文， 不会被显示

*** 缩略语

	<abbr>  光标移上去会出现提示
	<acronym> 首字母缩略词

*** 联系方式

	<address>

	
*** 上标和下标

	<sup>
	<sub>

*** 代码
	

    <code>: 用于标记计算机通用代码。
    <pre>: 用于保留空白字符（通常用于代码块）——如果您在文本中使用缩进或多余的空白，浏览器将忽略它，您将不会在呈现的页面上看到它。但是，如果您将文本包含在<pre></pre>标签中，那么空白将会以与你在文本编辑器中看到的相同的方式渲染出来。
    <var>: 用于标记具体变量名。
    <kbd>: 用于标记输入电脑的键盘（或其他类型）输入。
    <samp>: 用于标记计算机程序的输出。

*** 标记时间和日期

	<time>

** 文档与网站架构

   页眉
   导航
   主内容
   侧边栏
   页脚

   <header>：页眉。
   <nav>：导航栏。
   <main>：主内容。主内容中还可以有各种子内容区段，可用<article>、<section> 和 <div> 等元素表示。
   <aside>：侧边栏，经常嵌套在 <main> 中。
   <footer>：页脚

*** 布局元素   
    <main> 存放每个页面独有的内容。每个页面上只能用一次 <main>，且直接位于 <body> 中。最好不要把它嵌套进其它元素。
    <article> 包围的内容即一篇文章，与页面其它部分无关（比如一篇博文）。
    <section> 与 <article> 类似，但 <section> 更适用于组织页面使其按功能（比如迷你地图、一组文章标题和摘要）分块。一般的最佳用法是：以 标题 作为开头；也可以把一篇 <article> 分成若干部分并分别置于不同的 <section> 中，也可以把一个区段 <section> 分成若干部分并分别置于不同的 <article> 中，取决于上下文。
    <aside> 包含一些间接信息（术语条目、作者简介、相关链接，等等）。
    <header> 是简介形式的内容。如果它是 <body> 的子元素，那么就是网站的全局页眉。如果它是 <article> 或<section> 的子元素，那么它是这些部分特有的页眉（此 <header> 非彼 标题）。
    <nav> 包含页面主导航功能。其中不应包含二级链接等内容。
    <footer> 包含了页面的页脚部分。

*** 无语义元素

	<div> 和 <span> ， 配合使用 class 属性提供一些标签，使这些元素能易于查询。
	<span> 是内联无语义元素
	<div> 块级无语义元素

*** 换行和水平分割
	<br> 可在段落中进行换行；
	<br> 是唯一能够生成多个短行结构（例如邮寄地址或诗歌）的元素

	<hr> 元素在文档中生成一条水平分割线

** 调试
   
   
